# Generated by Django 5.1.2 on 2024-11-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_attractionimage_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttractionImage',
        ),
    ]
