# Generated by Django 5.1.2 on 2024-11-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_delete_attractionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='perfume_images/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
