# Generated by Django 5.1.2 on 2024-11-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_perfumeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfumeImage',
        ),
    ]
