# Generated by Django 5.1.2 on 2024-11-13 14:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_homepagecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='description',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='content',
            field=ckeditor.fields.RichTextField(default='<p>Welcome to the homepage!</p>'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
