# Generated by Django 5.1.2 on 2024-11-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=255, verbose_name='Head Title')),
                ('sub_title', models.CharField(max_length=255, verbose_name='Sub Title')),
                ('about_us', models.TextField(verbose_name='About Us Section')),
                ('shipping_info', models.TextField(verbose_name='Shipping Information')),
                ('order_now', models.TextField(verbose_name='Order Now Section')),
            ],
        ),
    ]
