# Generated by Django 5.1.2 on 2024-11-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_remove_pagecontent_shipping_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaggleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadra_title', models.CharField(help_text='Main title displayed in header', max_length=255)),
                ('sub_quadra_title', models.CharField(help_text='Subtitle displayed under main title', max_length=255)),
                ('narrative_section', models.TextField(help_text='Text content for the about us section')),
                ('delivery_info', models.TextField(help_text='Shipping and delivery information')),
                ('order_instructions', models.TextField(help_text='Order now and contact details')),
            ],
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
